-- ============================================================
-- FlowLedger - V1 Initial Schema
-- ============================================================

-- ============================================================
-- USERS
-- ============================================================

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       uuid UUID NOT NULL DEFAULT gen_random_uuid(),

                       email VARCHAR(255) NOT NULL,
                       password_hash VARCHAR(255) NOT NULL,

                       first_name VARCHAR(100) NOT NULL,
                       last_name VARCHAR(100) NOT NULL,

                       role VARCHAR(30) NOT NULL DEFAULT 'USER',
                       status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

                       created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                       CONSTRAINT uk_users_uuid UNIQUE (uuid),
                       CONSTRAINT uk_users_email UNIQUE (email),

                       CONSTRAINT chk_users_role
                           CHECK (role IN ('USER', 'ADMIN')),

                       CONSTRAINT chk_users_status
                           CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DELETED'))
);


-- ============================================================
-- WALLETS
-- ============================================================

CREATE TABLE wallets (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         uuid UUID NOT NULL DEFAULT gen_random_uuid(),

                         user_id BIGINT NOT NULL,

                         currency VARCHAR(3) NOT NULL DEFAULT 'IRR',

                         balance NUMERIC(19, 4) NOT NULL DEFAULT 0,

                         status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

                         version BIGINT NOT NULL DEFAULT 0,

                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                         CONSTRAINT uk_wallets_uuid UNIQUE (uuid),

                         CONSTRAINT fk_wallets_user
                             FOREIGN KEY (user_id)
                                 REFERENCES users(id),

                         CONSTRAINT chk_wallets_balance
                             CHECK (balance >= 0),

                         CONSTRAINT chk_wallets_status
                             CHECK (status IN ('ACTIVE', 'FROZEN', 'CLOSED')),

                         CONSTRAINT chk_wallets_currency
                             CHECK (currency IN ('IRR', 'USD', 'EUR'))
);


-- ============================================================
-- TRANSFERS
-- ============================================================

CREATE TABLE transfers (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                           uuid UUID NOT NULL DEFAULT gen_random_uuid(),

                           sender_wallet_id BIGINT NOT NULL,
                           receiver_wallet_id BIGINT NOT NULL,

                           amount NUMERIC(19, 4) NOT NULL,

                           currency VARCHAR(3) NOT NULL,

                           status VARCHAR(30) NOT NULL DEFAULT 'PENDING',

                           idempotency_key VARCHAR(255) NOT NULL,

                           reference VARCHAR(255),

                           created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           completed_at TIMESTAMP WITH TIME ZONE,

                           CONSTRAINT uk_transfers_uuid UNIQUE (uuid),

                           CONSTRAINT uk_transfers_idempotency_key
                               UNIQUE (idempotency_key),

                           CONSTRAINT fk_transfers_sender
                               FOREIGN KEY (sender_wallet_id)
                                   REFERENCES wallets(id),

                           CONSTRAINT fk_transfers_receiver
                               FOREIGN KEY (receiver_wallet_id)
                                   REFERENCES wallets(id),

                           CONSTRAINT chk_transfers_amount
                               CHECK (amount > 0),

                           CONSTRAINT chk_transfers_currency
                               CHECK (currency IN ('IRR', 'USD', 'EUR')),

                           CONSTRAINT chk_transfers_status
                               CHECK (status IN (
                                                 'PENDING',
                                                 'COMPLETED',
                                                 'FAILED',
                                                 'CANCELLED'
                                   )),

                           CONSTRAINT chk_transfers_different_wallets
                               CHECK (sender_wallet_id <> receiver_wallet_id)
);


-- ============================================================
-- LEDGER ENTRIES
-- ============================================================

CREATE TABLE ledger_entries (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                uuid UUID NOT NULL DEFAULT gen_random_uuid(),

                                wallet_id BIGINT NOT NULL,

                                transfer_id BIGINT,

                                type VARCHAR(10) NOT NULL,

                                amount NUMERIC(19, 4) NOT NULL,

                                currency VARCHAR(3) NOT NULL,

                                created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                CONSTRAINT uk_ledger_entries_uuid UNIQUE (uuid),

                                CONSTRAINT fk_ledger_wallet
                                    FOREIGN KEY (wallet_id)
                                        REFERENCES wallets(id),

                                CONSTRAINT fk_ledger_transfer
                                    FOREIGN KEY (transfer_id)
                                        REFERENCES transfers(id),

                                CONSTRAINT chk_ledger_type
                                    CHECK (type IN ('DEBIT', 'CREDIT')),

                                CONSTRAINT chk_ledger_amount
                                    CHECK (amount > 0),

                                CONSTRAINT chk_ledger_currency
                                    CHECK (currency IN ('IRR', 'USD', 'EUR'))
);


-- ============================================================
-- AUDIT LOGS
-- ============================================================

CREATE TABLE audit_logs (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                            uuid UUID NOT NULL DEFAULT gen_random_uuid(),

                            user_id BIGINT,

                            action VARCHAR(100) NOT NULL,

                            entity_type VARCHAR(100) NOT NULL,

                            entity_id UUID,

                            metadata JSONB,

                            ip_address INET,

                            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                            CONSTRAINT uk_audit_logs_uuid UNIQUE (uuid),

                            CONSTRAINT fk_audit_logs_user
                                FOREIGN KEY (user_id)
                                    REFERENCES users(id)
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_users_uuid
    ON users(uuid);

CREATE INDEX idx_wallets_uuid
    ON wallets(uuid);

CREATE INDEX idx_wallets_user_id
    ON wallets(user_id);

CREATE INDEX idx_transfers_uuid
    ON transfers(uuid);

CREATE INDEX idx_transfers_sender_wallet_id
    ON transfers(sender_wallet_id);

CREATE INDEX idx_transfers_receiver_wallet_id
    ON transfers(receiver_wallet_id);

CREATE INDEX idx_transfers_status
    ON transfers(status);

CREATE INDEX idx_transfers_created_at
    ON transfers(created_at);

CREATE INDEX idx_ledger_entries_uuid
    ON ledger_entries(uuid);

CREATE INDEX idx_ledger_entries_wallet_id
    ON ledger_entries(wallet_id);

CREATE INDEX idx_ledger_entries_transfer_id
    ON ledger_entries(transfer_id);

CREATE INDEX idx_ledger_entries_created_at
    ON ledger_entries(created_at);

CREATE INDEX idx_audit_logs_uuid
    ON audit_logs(uuid);

CREATE INDEX idx_audit_logs_user_id
    ON audit_logs(user_id);

CREATE INDEX idx_audit_logs_created_at
    ON audit_logs(created_at);